/*
import java.lang.foreign.SymbolLookup;
import java.util.ArrayList;
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import Number;
import Symbol;

public class App {

    public static void main(String[] args) throws Exception {
        Scanner scanner = new Scanner(new File("/home/seyd/advent/3/app/src/main/java/input.txt"));
        ArrayList<ArrayList<Character>> array = new ArrayList<>();
        Map<Character, Integer> counts = new HashMap<>();
        Pattern numbersPattern = Pattern.compile("\\d+");
        Pattern symbolsPattern = Pattern.compile("[@#$%&*+=\\-\\/]");
        ArrayList<Number> numbers = new ArrayList<>();
        ArrayList<Symbol> symbols = new ArrayList<>();
        int lineNumber = 0;

        while (scanner.hasNextLine()) {
            String line = scanner.nextLine();
            array.add(lineNumber, line.toCharArray());
            Matcher numbersOnLine = numbersPattern.matcher(line);
            while (numbersOnLine.find()) {
                int begin = numbersOnLine.start();
                int end = numbersOnLine.start() + numbersOnLine.end();
                numbers.add(new Number(
                    line.substring(begin, end),
                    lineNumber,
                    begin,
                    end
                ));
            }
            Matcher symbolsOnLine = symbolsPattern.matcher(line);
            while(symbolsOnLine.find()) {
                int position = symbolsOnLine.start();
                symbols.add(new SymbolLookup() {
                    line.toCharArray()[position],
                    lineNumber,
                    position
                });
            }
            lineNumber++;
        }
        for(Character c: counts.keySet()) {
            System.out.println("Character: " + c + " Count: " + counts.get(c));
        }
    }
}
