/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.io.File;
import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;

public class App {

    public static void main(String[] args) throws Exception {
        Scanner scanner = new Scanner(new File("/home/seyd/advent/3/app/src/main/java/input.txt"));
        Map<Character, Integer> counts = new HashMap<>();
        while (scanner.hasNextLine()) {
            String line = scanner.nextLine();
            for(char c: line.toCharArray()) {
                String symbols = "@#$%&*+-/=";
                if (!symbols.contains(Character.toString(c))) {
                    counts.put(c, counts.getOrDefault(c, 0) + 1);
                }
            }
        }
        for(Character c: counts.keySet()) {
            System.out.println("Character: " + c + " Count: " + counts.get(c));
        }
    }
}
