import java.io.File;
import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class App {

    public static void main(String[] args) throws Exception{
        Scanner scanner = new Scanner(new File("/home/seyd/advent/2/app/src/main/java/input1.txt"));

        Map<String, Integer> barrier = new HashMap<>();
        barrier.put("red", 12);
        barrier.put("green", 13);
        barrier.put("blue", 14);

        int sum = 0;
        int power = 0;

        outer:
        while (scanner.hasNext()) {
            String line = scanner.nextLine();
            int gameNumber = Integer.parseInt(line.split(":")[0].split(" ")[1]);
            String[] samples = line.split(":")[1].split(";");
            Map<String, Integer> maxima = new HashMap<>();
            Map<String, Integer> minima = new HashMap<>();

            for(String sample: samples) {
                for(String die: sample.split(",")) {
                    Integer value = Integer.parseInt(die.strip().split(" ")[0].strip());
                    String color = die.strip().split(" ")[1];
                    maxima.put(color,Math.max(value, maxima.getOrDefault(color, 0)));
                    minima.put(color,Math.min(value, Integer.MAX_VALUE));
                }
            }
            int product = 1;
            for (Integer value: maxima.values()) {
                product *= value;
            }
            power += product;
            for (String key: barrier.keySet()) {
                if (maxima.getOrDefault(key, 0) > barrier.get(key)) {
                    continue outer;
                }
            }
            sum += gameNumber;

        }
        System.out.println(sum);
        System.out.println(power);
    }
}
